fix custom metadata serialisation
getporter/porter pull request #1295
Opened 2020-09-22 12:03 UTC by simongdavies

# What does this change
 Updates marshalling of customdata YAML in order that the data can be serialised to json 

# What issue does it fix
Closes #1292

# Notes for the reviewer
_Put any questions or notes for the reviewer here._

# Checklist
- [X] Unit Tests
- [ ] Documentation
- [ ] Schema (porter.yaml)

If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

[contributors]: /CONTRIBUTORS.md

2020-09-22 15:56 UTC, carolynvs commented
Hey Simon, the original bug that your created doesn't reproduce for me on porter `v0.29.0-31-g6ce58563`. Please take a look and if you can get it to error out, update the PR with a failing regression test for the creating the bundle.json.

A good spot for the test would be in `TestManifestConverter_generateCustomMetadata` https://github.com/getporter/porter/blob/main/pkg/cnab/config-adapter/adapter_test.go and then use code like below to write the file out.

```go
        f, err := p.Config.FileSystem.OpenFile(build.LOCAL_BUNDLE, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0644)
	defer f.Close()
	if err != nil {
		...
	}
	_, err = b.WriteTo(f)
        ...
```

2020-09-22 15:57 UTC, carolynvs requested changes
These aren't the right places to make the changes because we don't serialize the bundle.json from the Manifest directly. I've left a comment on the PR with further direction.

2020-09-23 12:28 UTC, simongdavies commented
@carolynvs I've made the changes, I left the tests in the manifest test as I modified a test that was already present

2020-09-28 15:11 UTC, carolynvs requested changes

2020-09-28 15:11 UTC, carolynvs commented on pkg/cnab/config-adapter/adapter_test.go
> +	val, ok := bun.Custom["foo"].(map[string]interface{})
This test should use the original code I pointed you to for Marshaling a bundle to json, not repeat the tests from the manifest test suite. What we need to ensure is that after your change that we have a regression test that checks that we can create bundle.json files that contain nested custom metadata structures.

So let's write the json, compare it to a known string in a testdata file and this should be all set! 👍

2020-10-05 17:12 UTC, carolynvs approved these changes
Looks great! Thanks for identifying and fixing this. 👍

2020-10-05 17:13 UTC, merged