Removed import path comments
getporter/porter pull request #1348
Opened 2020-10-29 15:11 UTC by kazishafin

# What does this change

Removed the import path comments as they aren't supported anymore.

# What issue does it fix
Open #1285 

# Notes for the reviewer

# Checklist
- [ ] Unit Tests
- [ ] Documentation
- [ ] Schema (porter.yaml)

If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

[contributors]: /CONTRIBUTORS.md

2020-11-01 04:39 UTC, iennae commented on .gitattributes
> +* text=auto eol=lf
adding a gitattributes file should probably be included in a separate commit rather than bundling in with the rest of the updates.

2020-11-01 04:42 UTC, iennae requested changes
Can you separate out the removing import path comments from the addition of the gitattributes file and the .svg file updates?

2020-11-02 21:44 UTC, kazishafin commented
> Thank you so much for cleaning up the import path comments! It's great to see this contribution to the project.
> 
> Can you separate out the removing import path comments from the addition of the gitattributes file and the .svg file updates?

2020-12-30 07:22 UTC, iennae commented
I'm going to go ahead and close this PR at this point. gitattributes has been added separately, and there are too many updates to other files that aren't needed in this PR.

2020-12-30 07:22 UTC, closed without merging