feat(*): support mixin config schema
getporter/porter pull request #1649
Opened 2021-06-21 19:29 UTC by vdice

# What does this change

* Adds support for mixin config schema
  * If a mixin already declares config schema, we validate it and inject it into Porter's schema
  * If a mixin does not declare config schema, we inject a default, which allows:
    * a config-less mixin declaration, e.g.
    ```
      mixins:
        - mymixin
     ```
    * arbitrary config for the mixin (useful for when the mixin has yet to define its own schema but does already support additional configuration), e.g.
    ```
      mixins:
        - mymixin:
            arbitraryConfig: true
    ```

See also a PR for the first non-`exec` mixin to declare its configuration: 

Follow-ups: If/when this all ends up looking good, we can create issues in the rest of the mixin repos in this org to define their config schema.

# What issue does it fix
Closes https://github.com/getporter/porter/issues/1341

# Notes for the reviewer

# Checklist
- [x] Unit Tests
- [ ] Documentation
- [ ] Schema (porter.yaml)

If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

[contributors]: https://porter.sh/src/CONTRIBUTORS.md

2021-06-21 21:23 UTC, carolynvs requested changes
Seems like whatever information that we are returning in the anyOf isn't enough for VS Code to provide proper autocomplete?

![Screen Shot 2021-06-21 at 4 22 13 PM](https://user-images.githubusercontent.com/1368985/122829690-ee59c300-d2ac-11eb-94d8-548e342393af.png)

2021-06-21 21:23 UTC, carolynvs commented on pkg/porter/schema.go
> +			if !ok && p.Debug {
oops

2021-06-21 21:47 UTC, vdice commented
Oh, shoot, I didn't think about the VS Code autocompletion for available mixin names themselves.  I was hoping to find an example where we do so, but it looks like the actions also have similar behavior.  Must be with our use of `items`... 

<img width="496" alt="Screen Shot 2021-06-21 at 3 43 41 PM" src="https://user-images.githubusercontent.com/9322017/122831857-b603b600-d2a7-11eb-88e9-93fb8905ea39.png">

2021-06-22 14:40 UTC, carolynvs commented
Just throwing out guesses but maybe if we set title or description it will use it for display?

2021-06-22 17:03 UTC, vdice commented
> Just throwing out guesses but maybe if we set title or description it will use it for display?

Great idea!  Have yet to find the winner from title, description, $id, but I'll keep tryin'!

2021-06-22 18:22 UTC, vdice commented
Ok, so I still have yet to crack the nut on how to add identifiers/names to the vs code auto-complete for json schema arrays.  Would you be amenable to tackling this in a follow-up issue, as it affects/is relevant to other sections of the manifest (actions, etc.)?

I've updated the PR with changes to help the VS Code UX on auto-complete.  We add the enum list of mixin strings and place this first in the `anyOf` schema array for mixins, so that it offers a helpful prompt from the get-go.  Then, when users enter a mixin and continue to add optional configuration, the corresponding mixin config schema will be used for validation.  WDYT?


<img width="518" alt="Screen Shot 2021-06-22 at 11 30 52 AM" src="https://user-images.githubusercontent.com/9322017/122979113-67602580-d354-11eb-8f1b-06b241c351a0.png">

<img width="527" alt="Screen Shot 2021-06-22 at 11 31 06 AM" src="https://user-images.githubusercontent.com/9322017/122979096-64653500-d354-11eb-811f-5d21ec6ddddd.png">

<img width="486" alt="Screen Shot 2021-06-22 at 11 31 22 AM" src="https://user-images.githubusercontent.com/9322017/122979068-5a433680-d354-11eb-83b5-1539759580e6.png">

<img width="1003" alt="Screen Shot 2021-06-22 at 12 05 02 PM" src="https://user-images.githubusercontent.com/9322017/122979061-57e0dc80-d354-11eb-88df-4ae4eeb8e74f.png">

2021-06-22 20:33 UTC, carolynvs commented
I actually still see the same funky array drop down even with the latest changes, though if I start typing a mixin, like `exTAB` I'll get `exec`.

I'm not in a hurry to get this in, the entire point is to make VS Code not be weird. So since this PR doesn't yet get us all the way there, maybe let's work with @itowlson to figure out what we need to do to make autocomplete work the way we'd like before merging anything.

2021-06-22 20:49 UTC, vdice commented
Ah, I misunderstood the original issue.  It stated `When I declare a mixin and define configuration for it, VS Code decides that it is invalid.`  So, I focused and fixed that issue, i.e., VS Code now supports mixin configuration to be defined (it will still yell 'invalid' when it actually is invalid -- but now we actually check the mixin config schema).

I'll move this to Draft and revisit when cycles allow, since we aren't in a time crunch.

2021-06-23 19:01 UTC, carolynvs commented
Sorry it wasn't clear! Yes, the issue is all driven by the desire for someone to be able to write a porter.yaml file with VS Code or another editor helping with autocomplete. They won't need to rely on our docs and examples as much and should be able to discover what's available and write manifests more confidently and quickly.

2021-07-28 22:55 UTC, itowlson commented
@vdice Carolyn asked me if I could provide any advice on this.  Can you post an example of the schema for `mixins`?  I can't quite work it out from the PR itself I'm afraid.  That will help clarify whether the issue lies with the schema or with VS Code/RH YAML's handling of the schema.

2022-09-02 01:09 UTC, carolynvs commented
I restarted with Vaughn's changes and through the power of time, trial and error, got VS code to mostly do what I wanted. Closing in favor of #2290

2022-09-02 01:09 UTC, closed without merging