doc(styles): Scroll menu and main content separately
getporter/porter pull request #1685
Opened 2021-07-25 15:08 UTC by thisisommore

# What does this change
Menu now scroll separately and finitely

https://user-images.githubusercontent.com/51229945/126903548-a8301981-1f28-4ada-a1ee-82f49d7c934c.mp4

# What issue does it fix
Closes #1682 

# Notes for the reviewer
In desktop the box shadow of `<a class="exit-off-canvas"></a>` interfaces ui of scroll bar
![porter-screenshot](https://user-images.githubusercontent.com/51229945/126903696-9249b5c3-fe45-4004-ae77-da4d85782756.png)
There are three options to fix this,
- Use custom scroll bar style
- Remove `<a class="exit-off-canvas"></a>` completly
-  Remove box shadow property, possibly this https://github.com/getporter/porter/blob/05332860d3ad92a05d30f740165e7609106c6c4e/docs/themes/porter/assets/sass/foundation/components/_offcanvas.scss#L280

Due to `<a class="exit-off-canvas"></a>` in my changes home page doesn't scroll when menu is open.

2021-07-26 02:52 UTC, thisisommore commented
@DARK-art108 @carolynvs would like to discuss this ?

2021-07-26 10:22 UTC, DARK-art108 commented
Awesome @thisisommore Looks good to me!

2021-07-26 10:23 UTC, DARK-art108 approved these changes
Looks good to merge!

2021-07-26 10:43 UTC, DARK-art108 commented
@thisisommore can you elaborate more on what you have **Note for the reviewer** as I see the desktop site is working fine after this fix!

2021-07-26 11:09 UTC, thisisommore commented
> @thisisommore can you elaborate more on what you have **Note for the reviewer** as I see the desktop site is working fine after this fix!

@DARK-art108 
Sorry if I was being unclear there,
The issue here is minor and is only visible when windows width is small (thats when left hidden menu is available) and can be ignored.
After making menu scrollable it gets it own scrollbar, and that scrollbar gets under the shadow of the element which is in right side.
For reference see this screenshot
![image](https://user-images.githubusercontent.com/51229945/126979304-7ec76012-4b8f-4e5b-80ae-22295c850d23.png)
and this screenshot after removing the element in side right which was causing shadow,
![image](https://user-images.githubusercontent.com/51229945/126979511-ec6b73db-fcc0-41db-b75a-ab66a7c15702.png)

2021-07-27 15:16 UTC, carolynvs requested changes
Thanks for fixing this!

I tested the site on a small screen, and can see the problem that you highlighted with scrolling when the menu is open. I tried removing the exist-off-canvas and that seemed to fix it without any side-effects. 

Can you remove that element as well?

2021-07-27 17:00 UTC, thisisommore commented
> Thanks for fixing this!
> 
> I tested the site on a small screen, and can see the problem that you highlighted with scrolling when the menu is open. I tried removing the exist-off-canvas and that seemed to fix it without any side-effects. 
> 
> Can you remove that element as well?

I can remove that element by tomorrow and thanks for checking this out 😀, between I see that you have self assigned this, did you already removed element ?

2021-07-27 17:16 UTC, carolynvs commented
We use the assignment field on pull requests to help track which maintainer is "managing" a pull request, it doesn't mean that we are taking over an issue or anything. 😀

2021-07-27 17:22 UTC, thisisommore commented
> We use the assignment field on pull requests to help track which maintainer is "managing" a pull request, it doesn't mean that we are taking over an issue or anything. 😀 

Thanks, got it.

2021-07-28 03:39 UTC, thisisommore commented
I have removed the element from where it was causing issue, I didn't removed it from all html files since I am not aware of issues that might occur by removing the element from every file.

2021-07-28 05:34 UTC, DARK-art108 commented
@thisisommore it's working fine now in small screens, now site look more awesome!

2021-07-28 12:20 UTC, thisisommore commented
Just noticed, we are having issues with scroll in side menu.
Reference https://developers.google.com/web/updates/2016/12/url-bar-resizing
I will try to fix this.

2021-07-28 12:57 UTC, thisisommore commented
Now even more stable.
Chrome url bar now won't cause issues.
https://user-images.githubusercontent.com/51229945/127325805-ad3e41a2-0424-48f2-9642-79feff617439.mp4

2021-07-28 13:16 UTC, DARK-art108 approved these changes
Looks fine to me!

2021-07-28 21:55 UTC, carolynvs approved these changes
This looks great. I really appreciate you contributing some much needed CSS and design skills to our site. 👍

2021-07-28 21:55 UTC, carolynvs commented on CONTRIBUTORS.md
> +* [Om More](https://github.com/thisisommore)
Thank you for adding your name to our contributors page! 🎉

2021-07-28 21:55 UTC, merged