Print sensitive values if show-sensitive flag is set
getporter/porter pull request #1729
Opened 2021-08-21 07:53 UTC by ThorstenHans

# What does this change

This PR adds the `show-sensitive` persistent flag on the root command. It's defaulting to `false`

If the flag is set to `true`, sensitive values won't be masked in the output, instead they'll be directly written to the output.

# What issue does it fix
Closes #1708 

# Checklist
- [x] Unit Tests
- [ ] Documentation
- [ ] Schema (porter.yaml)

2021-08-21 07:53 UTC, ThorstenHans commented
Have to update the docs before submitting this for a review

2021-08-24 15:38 UTC, carolynvs requested changes

2021-08-24 15:38 UTC, carolynvs commented on pkg/context/context.go
> +	if len(vals) > 0 && !c.ShowSensitiveValues {
This function is used to update the censored writer with new values to *** out of the logs, when they are written later. When ShowSensitiveValues is true, we can preemptively exit the function without further changes.

The changes here will immediately print the sensitive values from the disallow list to the console, which isn't appropriate for this function.

2021-08-24 15:38 UTC, carolynvs commented on pkg/context/context_test.go
> +func TestContext_SetSensitiveValues(t *testing.T) {
To test this change, we want to do make a test context like you have done below, but then we should try two cases: setting some sensitive values and then writing to the context's Out and Err fields. Based on the value of ShowSensitiveValues, the captured output should either display *** in place of the sensitive values set, or print them without alteration.

2021-09-09 21:33 UTC, carolynvs commented
@ThorstenHans No rush but I wanted to check in to see if you need some help with this, or if any of my feedback was unclear.

2022-01-31 18:54 UTC, carolynvs commented
@ThorstenHans Would you be okay with me adding some commits to your branch to finish this PR so we can merge it?

2022-02-01 09:39 UTC, ThorstenHans commented
sure @carolynvs  and sorry for letting this PR in that state 😔

2022-02-01 15:57 UTC, carolynvs commented
Hey no worries! Everyone is busy and it's always nice to collaborate with people on a feature.

2024-09-24 07:34 UTC, kichristensen commented
Closed because of lack of activity. Please create a new PR if needed.

2024-09-24 07:34 UTC, closed without merging