1757  completion command
getporter/porter pull request #1844
Opened 2021-12-30 13:02 UTC by mikebarkas

# What does this change
This adds the standard Cobra completion command to Porter.

Example:
### Initial setup
`porter completion bash > /path/to/shell/completion/files/porter`

### Usage
```
porter bu[tab][tab]

build bundles
```

# What issue does it fix
Closes # 1757

# Notes for the reviewer

This also adds a test to ensure it completes without error.

This does not include dynamic querying for custom completions.

I also created setup and usage documentation on the bottom of the `/install` web page.

# Checklist
- [x] Unit Tests
- [x] Documentation
- [ ] Schema (porter.yaml)

2022-01-03 16:02 UTC, carolynvs requested changes
This is great! Thank you so much for adding it in and documenting how to use it.

The test just needs a little tweak and then this is ready to merge.

2022-01-03 16:57 UTC, mikebarkas commented on cmd/porter/completion.go
> +				cmd.Root().GenBashCompletion(os.Stdout)
Sounds good. I will make the change.

2022-01-03 16:57 UTC, mikebarkas commented on cmd/porter/completion.go
> +		Long:                  "Capture the output of the completion command to a file for your shell environment.",
Sounds good. I will make the change.

2022-01-03 16:59 UTC, mikebarkas commented on cmd/porter/completion_test.go
> +		require.NoError(t, err)
Thank you for the detailed feedback and guidance. I will make the changes.

2022-01-03 22:50 UTC, mikebarkas commented on cmd/porter/completion.go
> +		Long:                  "Capture the output of the completion command to a file for your shell environment.",
This is my change. I felt it was too long for one line.

```
porter completion --help
Save the output of this command to a file and load the file into your shell.
For additional details see: https://porter.sh/install#command-completion

Usage:
  porter completion [bash|zsh|fish|powershell]

Examples:
porter completion bash > /usr/local/etc/bash_completions.d/porter

Flags:
  -h, --help   help for completion

Global Flags:
      --debug           Enable debug logging
      --debug-plugins   Enable plugin debug logging```

2022-01-03 22:57 UTC, mikebarkas commented on cmd/porter/completion.go
> +				cmd.Root().GenBashCompletion(os.Stdout)
I see it documented here: https://porter.sh/contribute/guide/#logging

2022-01-03 23:09 UTC, mikebarkas commented
I made the requested changes and updated this PR.
This is ready for review again.

2022-01-04 18:25 UTC, carolynvs approved these changes
Thank you for adding this! 💯

2022-01-04 18:26 UTC, merged