use relocation map for pulling images during archive
getporter/porter pull request #2149
Opened 2022-06-09 19:57 UTC by VinozzZ

# What does this change
_Give a summary of the change, and how it affects end-users. It's okay to copy/paste your commit messages._

_For example if it introduces a new command or modifies a commands output, give an example of you running the command and showing real output here._

# What issue does it fix
Closes # _(issue)_

_If there is not an existing issue, please make sure we have context on why this change is needed. See our Contributing Guide for [examples of when an existing issue isn't necessary][1]._

[1]: https://porter.sh/src/CONTRIBUTING.md#when-to-open-a-pull-request

# Notes for the reviewer
_Put any questions or notes for the reviewer here._

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://porter.sh/src/CONTRIBUTORS.md

2022-06-09 21:10 UTC, carolynvs commented on pkg/porter/archive.go
> +	ctx, log := tracing.StartSpan(ctx)
Thank you for adding tracing in all your PRs! 💖

2022-06-16 19:43 UTC, carolynvs commented on pkg/porter/archive_test.go
> +			require.Equal(t, tc.hasError, err != nil)
Can you switch from just checking that an error occurred to checking for a substring in the error message You can use the tests.RequireErrorContains helper. That way we can be sure that it failed for the reason we were expecting.

2022-06-16 19:43 UTC, carolynvs commented on tests/integration/archive_test.go
> +	_, err = p.FileSystem.Stat(filepath.Join(tmpDir, strings.TrimSuffix(filepath.Base(source), ".tgz"), "relocation-mapping.json"))
I feel like this isn't giving us as much test coverage as we need here. For example, the test would pass if relocation-mapping.json is empty right? 

Can you add a check that it has the expected images in it as well?

2022-06-17 15:53 UTC, carolynvs requested changes

2022-06-17 18:27 UTC, VinozzZ commented on tests/smoke/archive_test.go
> +	newRef := "localhost:5000/copy-new-mydb:v0.1.1"
Thank you for the suggestion. I made the change accordingly

2022-06-20 15:54 UTC, carolynvs approved these changes
Thanks for updating the smoke test so that it's a regression test for this bug! Looks great and I'm excited to see us closing all these little gaps in getting airgapped bundles to work as intended. 💯

2022-06-20 15:54 UTC, merged