[Draft]: Shared Dependencies: the LOGIC
getporter/porter pull request #2940
Opened 2023-10-09 17:05 UTC by schristoff

2023-10-09 17:05 UTC, schristoff commented on pkg/porter/parameters.go
>  				// TODO(carolynvs): does this need to take namespace into account
Yes, but not namespace prob group name?

2023-11-28 07:52 UTC, schristoff commented on build/testdata/bundles/wordpress/porter.yaml
> +# outputs:
put this back

2023-11-28 08:33 UTC, schristoff commented on pkg/porter/parameters.go
>  				// TODO(carolynvs): does this need to take namespace into account
Yes, but I don't know what to do with it yet. If we name every related bundle with a prefix of the group name, this makes it easier to filter on. But we also have to deal with on deletes how do we handle child/parent relationship, esp. if the child has multiple parents?

2023-12-05 19:38 UTC, arschles approved these changes
This LGTM. I only have documentation nits.

2023-12-05 19:38 UTC, arschles commented on docs/content/docs/development/authoring-a-bundle/working-with-dependencies.md
> +is an experimental feature. Proceed with caution.
```suggestion
The second version of dependencies -- also called "shared dependencies" or DependenciesV2 -- is available under the [**experimental** flag](https://porter.sh/docs/configuration/configuration/#experimental-feature-flags), and therefore an experimental feature. Please proceed with caution.
```

2023-12-05 19:38 UTC, arschles commented on docs/content/docs/development/authoring-a-bundle/working-with-dependencies.md
> +by setting an environment variable:
```suggestion
You can enable the experimental flag, thus enabling DependenciesV2, by setting an environment variable as follows:
```

2023-12-05 19:38 UTC, arschles commented on docs/content/docs/development/authoring-a-bundle/working-with-dependencies.md
> +The configuration for dependenciesv2 is similar to v1, except now there is the "sharing" section which has the required fields of "mode", and "group" "name".
```suggestion
The configuration for DependenciesV2 is similar to that of the first version, except there is now a "sharing" section with the following required fields: `mode`, `group.name`.
```

2023-12-05 19:38 UTC, arschles commented on docs/content/docs/development/authoring-a-bundle/working-with-dependencies.md
> +Mode is a boolean, and group name is the identifier which will allow for certain
```suggestion
`mode` is a boolean, and `group.name` is the identifier which will allow for certain
```

2023-12-05 19:38 UTC, arschles commented on docs/content/docs/development/authoring-a-bundle/working-with-dependencies.md
> +of "sh.porter.SharingGroup" and the value of the group name specified in the parent bundle. The existing dependency **must** be successfully installed. If it is uninstalled this must be deleted by th
```suggestion
If there is an existing dependency installed that the parent bundle should connect to, you must create a label for the existing dependency with the `sh.porter.SharingGroup` key, and the value of the group name specified in the parent bundle. The existing dependency **must** be successfully installed. If it is uninstalled this key must be deleted by the users before the operation can proceed. 
```

2023-12-05 19:38 UTC, arschles commented on pkg/cnab/dependencies/v1/doc.go
should this file just be deleted? I can't tell from this diff it is is or not

2023-12-05 19:38 UTC, arschles commented on pkg/cnab/extended_bundle.go
> +		//todo(schristoff): We should 100% move this logic into
```suggestion
		// todo(schristoff): We should 100% move this logic into
```

2023-12-05 20:48 UTC, schristoff commented on pkg/cnab/dependencies/v1/doc.go
I don't... know. But I think not?

2023-12-05 21:05 UTC, devigned requested changes
Mostly documentation feedback. I caught a couple spelling issues. I could have missed others, so might want to run through spellchecker.

Nice work!!

2023-12-05 21:11 UTC, schristoff commented on pkg/cnab/extended_bundle.go
> +			return nil, fmt.Errorf("dont do this")
lol whoops thank you

2023-12-06 02:02 UTC, merged