chore: remove self hosted runner try 2
getporter/porter pull request #2976
Opened 2024-02-02 19:33 UTC by schristoff

2024-02-02 19:39 UTC, troy0820 requested changes
You may have to put this on the line or unindent this.

2024-02-02 19:39 UTC, troy0820 commented on .github/workflows/build_pipelinesrelease_template.yml
> +      - ubunut-latest
You may have to unindent this.

2024-02-02 19:39 UTC, troy0820 commented on .github/workflows/build_pipelinesrelease_template.yml
> +      - ubunut-latest
```suggestion
    - ubunut-latest
```

2024-02-03 18:28 UTC, schristoff commented
you got it in one of your PRs 🫡

2024-02-03 18:28 UTC, closed without merging